dae_conv_tiny:
  model_name: "dae_conv_tiny"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [32, 64, 128]
  decoder_channels: [128, 64, 32]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_small:
  model_name: "dae_conv_small"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [64, 128, 256]
  decoder_channels: [256, 128, 64]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_base:
  model_name: "dae_conv_base"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [128, 256, 512]
  decoder_channels: [512, 256, 128]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_large:
  model_name: "dae_conv_large"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [256, 512, 1024]
  decoder_channels: [1024, 512, 256]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_huge:
  model_name: "dae_conv_huge"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [512, 1024, 2048]
  decoder_channels: [2048, 1024, 512]
  gate: "Sigmoid"
  noise_factor: 0.2

