dae_vit_tiny:
  model_name: "dae_vit_tiny"
  patch_size: 4
  emb_dim: 96
  encoder_layer: 12
  encoder_head: 3
  decoder_layer: 4
  decoder_head: 3

dae_vit_small:
  model_name: "dae_vit_small"
  patch_size: 4
  emb_dim: 192
  encoder_layer: 12
  encoder_head: 3
  decoder_layer: 4
  decoder_head: 3

dae_vit_base:
  model_name: "dae_vit_base"
  patch_size: 4
  emb_dim: 384
  encoder_layer: 12
  encoder_head: 6
  decoder_layer: 4
  decoder_head: 6

dae_vit_large:
  model_name: "dae_vit_large"
  patch_size: 4
  emb_dim: 768
  encoder_layer: 12
  encoder_head: 12
  decoder_layer: 4
  decoder_head: 12

dae_vit_huge:
  model_name: "dae_vit_huge"
  patch_size: 4
  emb_dim: 1024
  encoder_layer: 24
  encoder_head: 16
  decoder_layer: 8
  decoder_head: 16

dae_resnet_18:
  model_name: "dae_resnet_18"

dae_resnet_34:
  model_name: "dae_resnet_34"

dae_resnet_50:
  model_name: "dae_resnet_50"

dae_resnet_101:
  model_name: "dae_resnet_101"

dae_resnet_152:
  model_name: "dae_resnet_152"
