# dae_vit_tiny:
#   model_name: "dae_vit_tiny"
#   emb_dim: 96
#   encoder_layer: 12
#   encoder_head: 3
#   decoder_layer: 8
#   decoder_head: 6

# dae_vit_small:
#   model_name: "dae_vit_small"
#   emb_dim: 192
#   encoder_layer: 12
#   encoder_head: 6
#   decoder_layer: 8
#   decoder_head: 8

# dae_vit_base:
#   model_name: "dae_vit_base"
#   emb_dim: 384
#   encoder_layer: 12
#   encoder_head: 12
#   decoder_layer: 8
#   decoder_head: 16

# dae_vit_large:
#   model_name: "dae_vit_large"
#   emb_dim: 768
#   encoder_layer: 24
#   encoder_head: 16
#   decoder_layer: 16
#   decoder_head: 16

# dae_vit_huge:
#   model_name: "dae_vit_huge"
#   emb_dim: 1024
#   encoder_layer: 32
#   encoder_head: 16
#   decoder_layer: 16
#   decoder_head: 16

dae_conv_tiny:
  model_name: "dae_conv_tiny"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [32, 64, 128]
  decoder_channels: [128, 64, 32]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_small:
  model_name: "dae_conv_small"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [64, 128, 256]
  decoder_channels: [256, 128, 64]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_base:
  model_name: "dae_conv_base"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [128, 256, 512]
  decoder_channels: [512, 256, 128]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_large:
  model_name: "dae_conv_large"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [256, 512, 1024]
  decoder_channels: [1024, 512, 256]
  gate: "Sigmoid"
  noise_factor: 0.2

dae_conv_huge:
  model_name: "dae_conv_huge"
  in_channels: 3
  img_size: 224
  kernel_size: 3
  encoder_channels: [512, 1024, 2048]
  decoder_channels: [2048, 1024, 512]
  gate: "Sigmoid"
  noise_factor: 0.2

